<!doctype html>
<script>window.teacherPhotos=@json($teachers);window.teacherAssetBase='{{ asset('') }}';</script><script defer src="{{ asset('teacher-photos.js') }}?v={{ filemtime(public_path('teacher-photos.js')) }}"></script>
<link rel="stylesheet" href="{{ asset('teacher-photo.css') }}?v={{ filemtime(public_path('teacher-photo.css')) }}">
<script defer src="{{ asset('mobile-nav.js') }}?v={{ filemtime(public_path('mobile-nav.js')) }}"></script>
<script defer src="{{ asset('section-animations.js') }}?v={{ filemtime(public_path('section-animations.js')) }}"></script>
<script>window.youtubeProfileUrl=@json(array_replace(config('school'), $school)['profile_video_url'] ?? '');</script><script defer src="{{ asset('youtube-video.js') }}?v={{ filemtime(public_path('youtube-video.js')) }}"></script>
<script defer src="{{ asset('program-card-icons.js') }}?v={{ filemtime(public_path('program-card-icons.js')) }}"></script>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Website resmi {{ $school['name'] }} — sekolah unggul dan berkarakter."><title>{{ $school['name'] }}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,600;0,700;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('style.css') }}?v={{ filemtime(public_path('style.css')) }}"><link rel="stylesheet" href="{{ asset('animations.css') }}"></head>
<body><header class="site-header" id="top"><div class="container navbar"><a class="brand" href="#top"><div class="brand-mark">{{ $school['initials'] }}</div><div><strong>{{ $school['short_name'] }}</strong><span>{{ $school['level'] }}</span></div></a><button class="menu-toggle" aria-label="Buka menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="nav-menu"><a href="#profil">Profil</a><a href="#visi-misi">Visi & Misi</a><a href="#program">Akademik</a><a href="#guru">Guru</a><a href="#berita">Berita</a><a class="nav-cta" href="#kontak">{{ $school['ppdb_label'] }}</a></nav></div></header>
<main>
<section class="hero"><div class="hero-copy"><div class="hero-kicker"><span></span> {{ $school['hero_announcement'] }}</div><div class="eyebrow">{{ $school['level'] }}</div><h1>{{ $school['short_name'] }}<span>.</span></h1><p>{{ $school['tagline'] }}</p><div class="hero-actions"><a class="btn btn-primary" href="#kontak">{{ $school['hero_primary_button'] }}</a><a class="btn btn-link" href="#profil">{{ $school['hero_secondary_button'] }} <span>→</span></a></div><div class="mini-feature"><div class="mini-icon">✦</div><div><strong>{{ $school['hero_feature_title'] }}</strong><span>{{ $school['hero_feature_text'] }}</span></div></div></div><div class="hero-visual" style="background-image:url('{{ asset($school['hero_image']) }}')"><div class="hero-overlay"></div><div class="hero-caption"><span>01</span> {{ $school['hero_caption'] }}</div><div class="floating-card">@for($i=1;$i<=3;$i++)<div><strong>{{ $school['hero_stat_'.$i.'_value'] }}</strong><span>{{ $school['hero_stat_'.$i.'_label'] }}</span></div>@endfor</div></div></section>
<section class="trust-strip"><div class="container trust-grid">@for($i=1;$i<=4;$i++)<div><strong>{{ $school['trust_'.$i.'_value'] }}</strong><span>{{ $school['trust_'.$i.'_label'] }}</span></div>@endfor</div></section>
<section class="section about" id="profil"><div class="container two-col"><div class="image-stack"><img src="{{ asset($school['profile_image']) }}" alt="Lingkungan sekolah"><div class="experience-badge"><strong>{{ $school['experience_years'] }}</strong><span>tahun mendidik<br>generasi bangsa</span></div><div class="quote-card">“{{ $school['principal_quote'] }}”</div></div><div class="section-copy"><div class="eyebrow">Profil Sekolah</div><h2>{{ $school['profile_title'] }}</h2><p>{{ $school['profile'] }}</p><div class="check-grid">@foreach(preg_split('/\R/',$school['benefits']) as $benefit)<span>✓ {{ $benefit }}</span>@endforeach</div><p class="principal-sign"><strong>{{ $school['principal'] }}</strong><br><small>Kepala Sekolah</small></p></div></div></section>
@php($missions = array_values(array_filter(array_map('trim', preg_split('/\R+/', $school['mission'] ?? '')))))
<section class="section vision" id="visi-misi"><div class="container"><div class="section-heading"><div><div class="eyebrow">Arah Pendidikan</div><h2>Visi dan Misi Sekolah</h2></div><p>Landasan dan langkah utama {{ $school['short_name'] }} dalam mendampingi setiap siswa.</p></div><div class="vision-layout"><article class="vision-card"><div class="vision-card-label"><b>01</b><span>VISI SEKOLAH</span></div><h3>{{ $school['vision'] ?? '' }}</h3></article><div class="mission-block"><div class="mission-heading"><b>02</b><div><span>MISI SEKOLAH</span><p>Langkah yang dilakukan untuk mewujudkan visi sekolah.</p></div></div><div class="mission-list">@forelse($missions as $index => $mission)@php([$missionTitle, $missionDescription] = array_pad(array_map('trim', explode('|', $mission, 2)), 2, ''))<article><b>{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</b><div><h3>{{ $missionTitle }}</h3>@if($missionDescription)<p>{{ $missionDescription }}</p>@endif</div></article>@empty<article><b>01</b><div><h3>Misi sekolah belum diisi.</h3></div></article>@endforelse</div></div></div></div></section>
<section class="section programs" id="program"><div class="container"><div class="section-heading"><div><div class="eyebrow">Program Unggulan</div><h2>Belajar lebih relevan, aktif, dan bermakna.</h2></div><p>Program menggabungkan kompetensi akademik dengan komunikasi, kreativitas, kolaborasi, dan kepemimpinan.</p></div><div class="card-grid">@foreach($programs as $index => $program)<article class="program-card {{ $index===1?'featured':'' }}"><span class="card-number">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</span><div class="icon-box">{{ $program['icon'] ?? '✦' }}</div><h3>{{ $program['title'] }}</h3><p>{{ $program['description'] }}</p><a href="#kontak">Tanya program →</a></article>@endforeach</div></div></section>
<section class="section teachers" id="guru"><div class="container"><div class="section-heading compact"><div><div class="eyebrow">Guru & Tenaga Pendidik</div><h2>Didampingi orang-orang yang peduli.</h2></div><p>Guru hadir sebagai pengajar, mentor, dan rekan tumbuh bagi setiap siswa.</p></div><div class="teacher-grid">@foreach($teachers as $index => $teacher)<article class="teacher-card"><div class="teacher-avatar avatar-{{ $teacher['color'] ?? ['navy','gold','green','plum'][$index%4] }}">{{ $teacher['initials'] ?? collect(explode(' ',$teacher['name']))->map(fn($word)=>strtoupper(substr($word,0,1)))->take(2)->implode('') }}</div><h3>{{ $teacher['name'] }}</h3><span>{{ $teacher['role'] }}</span><p>{{ $teacher['description'] }}</p><div class="teacher-meta"><b>{{ $teacher['specialty'] ?? $teacher['role'] }}</b><small>{{ $teacher['experience'] ?? '' }}</small></div></article>@endforeach</div><div class="teacher-note"><span>✦</span><p>“Guru terbaik menyalakan keinginan untuk terus belajar dan bertanya.”</p></div></div></section>
<section class="section facilities" id="fasilitas"><div class="container"><div class="section-heading"><div><div class="eyebrow">Fasilitas Sekolah</div><h2>Lingkungan belajar yang aman dan modern.</h2></div><p>Ruang yang mendukung siswa untuk belajar, bereksperimen, berkolaborasi, dan berkembang.</p></div><div class="facility-grid">@foreach($facilities as $index => $facility)<div class="facility {{ $index===0?'large':'' }}" style="background-image:url('{{ asset($facility['image']) }}')"><span>{{ $facility['name'] }}</span></div>@endforeach</div></div></section>
<section class="section news" id="berita"><div class="container"><div class="section-heading compact"><div><div class="eyebrow">Berita & Kegiatan</div><h2>Cerita terbaru dari sekolah.</h2></div><p>Klik berita untuk membaca kegiatan selengkapnya.</p></div><div class="news-grid">@foreach($news as $article)<a class="news-card news-link" href="{{ route('news.show', $article['slug']) }}"><div class="news-image" style="background-image:url('{{ asset($article['image']) }}')"></div><div class="news-content"><span class="news-tag">{{ $article['category'] }}</span><h3>{{ $article['title'] }}</h3><span class="read-more">Baca selengkapnya →</span></div></a>@endforeach</div></div></section>
<section class="testimonial"><div class="container testimonial-wrap"><div><div class="eyebrow light">Testimoni Orang Tua</div><blockquote>“Sekolah ini tidak hanya fokus pada nilai, tetapi juga membentuk rasa percaya diri, kedisiplinan, dan tanggung jawab anak kami.”</blockquote><div class="person"><strong>Rina Pratiwi</strong><span>Orang tua siswa kelas XI</span></div></div><div class="testimonial-badge"><strong>4.9/5</strong><span>Kepuasan Orang Tua</span></div></div></section>
<section class="section contact" id="kontak"><div class="container contact-box"><div><div class="eyebrow">Penerimaan Peserta Didik Baru</div><h2>Mulai perjalanan terbaikmu bersama {{ $school['short_name'] }}.</h2><p>Dapatkan informasi jadwal, biaya, beasiswa, dan prosedur pendaftaran tahun ajaran 2026/2027.</p></div><div class="contact-actions"><a class="btn btn-primary" href="https://wa.me/{{ $school['phone'] }}" target="_blank" rel="noopener">Hubungi WhatsApp</a><a class="btn btn-outline" href="mailto:{{ $school['email'] }}">Kirim Email</a></div></div></section>
</main><footer><div class="container footer-grid"><div><a class="brand footer-brand" href="#top"><div class="brand-mark">{{ $school['initials'] }}</div><div><strong>{{ $school['short_name'] }}</strong><span>{{ $school['level'] }}</span></div></a><p>{{ $school['address'] }}<br>Senin–Jumat, 07.00–16.00</p></div><div><h4>Informasi</h4><a href="#profil">Profil Sekolah</a><a href="#visi-misi">Visi & Misi</a><a href="#program">Akademik</a><a href="#fasilitas">Fasilitas</a></div><div><h4>Layanan</h4><a href="#kontak">PPDB Online</a><a href="{{ route('login') }}">Portal Sekolah</a><a href="#berita">Berita & Agenda</a></div><div><h4>Kontak</h4><a href="https://wa.me/{{ $school['phone'] }}">WhatsApp Sekolah</a><a href="mailto:{{ $school['email'] }}">{{ $school['email'] }}</a><p>{{ $school['address'] }}</p></div></div><div class="container copyright">© {{ date('Y') }} {{ $school['name'] }}. Seluruh hak cipta dilindungi.</div></footer><script src="{{ asset('script.js') }}"></script></body></html>
