<!doctype html>
<script defer src="{{ asset('admin-teacher-upload.js') }}?v={{ filemtime(public_path('admin-teacher-upload.js')) }}"></script>
<script defer src="{{ asset('admin-facility-upload.js') }}?v={{ filemtime(public_path('admin-facility-upload.js')) }}"></script>
<script defer src="{{ asset('admin-news-upload.js') }}?v={{ filemtime(public_path('admin-news-upload.js')) }}"></script>
<script defer src="{{ asset('admin-save-confirm.js') }}?v={{ filemtime(public_path('admin-save-confirm.js')) }}"></script>
<script>window.adminSuccessMessage = @json(session('success'));</script>
<script defer src="{{ asset('admin-success-animation.js') }}?v={{ filemtime(public_path('admin-success-animation.js')) }}"></script>
<link rel="stylesheet" href="{{ asset('admin-save-confirm.css') }}?v={{ filemtime(public_path('admin-save-confirm.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-success-animation.css') }}?v={{ filemtime(public_path('admin-success-animation.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-facility-upload.css') }}?v={{ filemtime(public_path('admin-facility-upload.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-save-visibility.css') }}?v={{ filemtime(public_path('admin-save-visibility.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-modal-footer.css') }}?v={{ filemtime(public_path('admin-modal-footer.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-actions.css') }}?v={{ filemtime(public_path('admin-actions.css')) }}">
<link rel="stylesheet" href="{{ asset('admin-table.css') }}?v={{ filemtime(public_path('admin-table.css')) }}"><link rel="stylesheet" href="{{ asset('admin-section-filter.css') }}?v={{ filemtime(public_path('admin-section-filter.css')) }}"><script defer src="{{ asset('admin-table-view.js') }}?v={{ filemtime(public_path('admin-table-view.js')) }}"></script><script defer src="{{ asset('admin-section-filter.js') }}?v={{ filemtime(public_path('admin-section-filter.js')) }}"></script>
<script defer src="{{ asset('admin-canonical-nav.js') }}?v={{ filemtime(public_path('admin-canonical-nav.js')) }}"></script>
<script defer src="{{ asset('admin-editor.js') }}?v={{ filemtime(public_path('admin-editor.js')) }}"></script>
<html lang="id">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Kelola Website Sekolah</title><link rel="stylesheet" href="{{ asset('admin.css') }}">
  <style>
  html{scroll-behavior:smooth}.admin-form{display:grid;gap:24px}.editor-section{scroll-margin-top:25px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.field{display:flex;flex-direction:column;gap:7px}.field.full{grid-column:1/-1}.field label{font-size:12px;font-weight:700;color:#52627a}.field input,.field textarea,.field select{width:100%;border:1px solid #d5dce6;border-radius:9px;padding:12px 13px;font:14px inherit;color:#203b61;background:#fff}.field textarea{min-height:100px;resize:vertical}.repeat-card{padding:18px;margin-top:14px;border:1px solid #e2e7ef;border-radius:12px;background:#f9fbfe}.repeat-card h3{margin:0 0 15px;color:#294a83}.section-head{display:flex;justify-content:space-between;gap:15px;align-items:start}.section-head h2{margin:0}.section-head p{margin:5px 0 18px;color:#75839a;font-size:13px}.notice{padding:13px 16px;border-radius:9px;margin-bottom:18px;background:#eef3ff;color:#35549b}.sticky-save{position:sticky;bottom:18px;display:flex;justify-content:flex-end;z-index:5}.sticky-save .mz-button{border:0;box-shadow:0 8px 28px rgba(54,83,170,.3)}.mz-nav a{scroll-behavior:smooth}@media(max-width:800px){.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.mz-sidebar{display:none}.mz-main{margin-left:0!important;padding:20px!important}}
  </style>
</head>
<body class="mz-body"><div class="mz-layout">
<aside class="mz-sidebar"><a class="mz-brand" href="{{ route('dashboard') }}"><span class="mz-logo">{{ config('school.initials') }}</span><span><strong>{{ config('school.short_name') }}</strong><small>ADMIN SEKOLAH</small></span></a><nav class="mz-nav"><div class="mz-caption">Menu utama</div><a href="{{ route('dashboard') }}">Dashboard</a><div class="mz-caption">Kelola website</div><a href="#profil">Profil sekolah</a><a href="#visi">Visi & misi</a><a href="#akademik">Program akademik</a><a href="#guru">Guru & pengajar</a><a href="#fasilitas">Fasilitas</a><a href="#berita">Berita & artikel</a><a href="#kontak">PPDB & kontak</a></nav><form method="POST" action="{{ route('logout') }}">@csrf<button class="mz-logout">Keluar dari admin</button></form></aside>
<main class="mz-main"><header class="mz-top"><div><p>Admin / Pengaturan website</p><h1>Kelola website sekolah</h1></div><a class="mz-button" href="{{ route('home') }}" target="_blank">Lihat website</a></header>
<div class="notice">{{ session('success') ?: ($errors->first() ?: 'Pilih bagian yang ingin diubah, lalu tekan Simpan Perubahan.') }}</div>
<?php
$school = array_replace(config('school'), $content['school'] ?? []);
$programs = array_pad($content['programs'] ?? [], 3, ['title'=>'','description'=>'']);
$teachers = array_pad($content['teachers'] ?? [], 4, ['name'=>'','role'=>'','description'=>'']);
$facilities = array_pad($content['facilities'] ?? [], 4, ['name'=>'','image'=>'']);
?>
<form class="admin-form" method="POST" enctype="multipart/form-data" action="{{ route('admin.content.update') }}">@csrf
<section class="mz-card editor-section" id="hero">
  <div class="section-head"><div><h2>Tampilan utama</h2><p>Atur seluruh teks, gambar, tombol, dan statistik pada bagian paling atas landing page.</p></div></div>
  <div class="form-grid">
    <div class="field full"><label>Pengumuman PPDB</label><input name="hero_announcement" value="{{ $school['hero_announcement'] }}"></div>
    <div class="field"><label>Nama sekolah pada judul</label><input name="short_name" value="{{ $school['short_name'] }}"></div>
    <div class="field"><label>Label tombol PPDB navbar</label><input name="ppdb_label" value="{{ $school['ppdb_label'] }}"></div>
    <div class="field full"><label>Tagline utama</label><textarea name="tagline">{{ $school['tagline'] }}</textarea></div>
    <div class="field"><label>Teks tombol utama</label><input name="hero_primary_button" value="{{ $school['hero_primary_button'] }}"></div>
    <div class="field"><label>Teks tombol kedua</label><input name="hero_secondary_button" value="{{ $school['hero_secondary_button'] }}"></div>
    <div class="field full"><label>Gambar utama</label><input type="file" name="hero_image_upload" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, atau WebP. Maksimal 4 MB. Gambar saat ini: {{ $school['hero_image'] }}</small></div>
    <div class="field full"><label>Keterangan pada gambar</label><input name="hero_caption" value="{{ $school['hero_caption'] }}"></div>
    <div class="field"><label>Judul kartu informasi</label><input name="hero_feature_title" value="{{ $school['hero_feature_title'] }}"></div>
    <div class="field"><label>Isi kartu informasi</label><input name="hero_feature_text" value="{{ $school['hero_feature_text'] }}"></div>
    @for($i = 1; $i <= 3; $i++)
      <div class="field"><label>Statistik gambar {{ $i }} — angka</label><input name="hero_stat_{{ $i }}_value" value="{{ $school['hero_stat_'.$i.'_value'] }}"></div>
      <div class="field"><label>Statistik gambar {{ $i }} — keterangan</label><input name="hero_stat_{{ $i }}_label" value="{{ $school['hero_stat_'.$i.'_label'] }}"></div>
    @endfor
    @for($i = 1; $i <= 4; $i++)
      <div class="field"><label>Statistik bawah {{ $i }} — angka</label><input name="trust_{{ $i }}_value" value="{{ $school['trust_'.$i.'_value'] }}"></div>
      <div class="field"><label>Statistik bawah {{ $i }} — keterangan</label><input name="trust_{{ $i }}_label" value="{{ $school['trust_'.$i.'_label'] }}"></div>
    @endfor
  </div>
</section>
<section class="mz-card editor-section" id="profil"><div class="section-head"><div><h2>Identitas & profil sekolah</h2><p>Data ini tampil langsung pada bagian Profil di landing page.</p></div></div><div class="form-grid"><div class="field"><label>Nama lengkap</label><input name="name" value="{{ $school['name'] }}"></div><div class="field"><label>Nama singkat</label><input name="short_name" value="{{ $school['short_name'] }}"></div><div class="field"><label>Jenjang</label><input name="level" value="{{ $school['level'] }}"></div><div class="field"><label>Inisial logo</label><input name="initials" maxlength="4" value="{{ $school['initials'] }}"></div><div class="field full"><label>Judul profil</label><input name="profile_title" value="{{ $school['profile_title'] }}"></div><div class="field full"><label>Deskripsi profil</label><textarea name="profile">{{ $school['profile'] }}</textarea></div><div class="field"><label>Gambar profil</label><input name="profile_image" value="{{ $school['profile_image'] }}"></div><div class="field"><label>Lama pengalaman</label><input name="experience_years" value="{{ $school['experience_years'] }}"></div><div class="field full"><label>Keunggulan — satu poin per baris</label><textarea name="benefits">{{ $school['benefits'] }}</textarea></div><div class="field"><label>Nama kepala sekolah</label><input name="principal" value="{{ $school['principal'] }}"></div><div class="field"><label>Sambutan singkat</label><input name="principal_quote" value="{{ $school['principal_quote'] }}"></div><div class="field full"><label>Tagline</label><input name="tagline" value="{{ $school['tagline'] }}"></div></div></section>
<section class="mz-card editor-section" id="visi"><div class="section-head"><div><h2>Visi & misi</h2><p>Arah dan tujuan pendidikan sekolah.</p></div></div><div class="form-grid"><div class="field full"><label>Visi sekolah</label><textarea name="vision">{{ $school['vision'] ?? '' }}</textarea></div><div class="field full"><label>Misi sekolah — satu misi per baris</label><textarea name="mission">{{ $school['mission'] ?? '' }}</textarea></div></div></section>
<section class="mz-card editor-section" id="akademik"><div class="section-head"><div><h2>Program akademik</h2><p>Program unggulan yang ditampilkan di landing page.</p></div></div>@foreach($programs as $i => $program)<div class="repeat-card"><h3>Program {{ $i+1 }}</h3><div class="form-grid"><div class="field"><label>Nama program</label><input name="programs[{{ $i }}][title]" value="{{ $program['title'] ?? '' }}"></div><div class="field full"><label>Deskripsi</label><textarea name="programs[{{ $i }}][description]">{{ $program['description'] ?? '' }}</textarea></div></div></div>@endforeach</section>
<section class="mz-card editor-section" id="guru"><div class="section-head"><div><h2>Guru & pengajar</h2><p>Profil lengkap tenaga pendidik yang tampil di landing page.</p></div></div>@foreach($teachers as $i => $teacher)<div class="repeat-card"><h3>Guru {{ $i+1 }}</h3><div class="form-grid"><div class="field"><label>Nama dan gelar</label><input name="teachers[{{ $i }}][name]" value="{{ $teacher['name'] ?? '' }}"></div><div class="field"><label>Jabatan / mata pelajaran</label><input name="teachers[{{ $i }}][role]" value="{{ $teacher['role'] ?? '' }}"></div><div class="field"><label>Inisial avatar</label><input maxlength="3" name="teachers[{{ $i }}][initials]" value="{{ $teacher['initials'] ?? '' }}" placeholder="AR"></div><div class="field"><label>Warna avatar</label><select name="teachers[{{ $i }}][color]"><option value="navy" {{ ($teacher['color']??'')==='navy'?'selected':'' }}>Biru navy</option><option value="gold" {{ ($teacher['color']??'')==='gold'?'selected':'' }}>Emas</option><option value="green" {{ ($teacher['color']??'')==='green'?'selected':'' }}>Hijau</option><option value="plum" {{ ($teacher['color']??'')==='plum'?'selected':'' }}>Ungu</option></select></div><div class="field"><label>Bidang keahlian</label><input name="teachers[{{ $i }}][specialty]" value="{{ $teacher['specialty'] ?? '' }}" placeholder="Manajemen Pendidikan"></div><div class="field"><label>Lama pengalaman</label><input name="teachers[{{ $i }}][experience]" value="{{ $teacher['experience'] ?? '' }}" placeholder="10 tahun"></div><div class="field full"><label>Deskripsi singkat</label><textarea name="teachers[{{ $i }}][description]">{{ $teacher['description'] ?? '' }}</textarea></div></div></div>@endforeach</section>
<section class="mz-card editor-section" id="fasilitas"><div class="section-head"><div><h2>Fasilitas</h2><p>Daftar fasilitas dan gambar pendukung.</p></div></div>@foreach($facilities as $i => $facility)<div class="repeat-card"><h3>Fasilitas {{ $i+1 }}</h3><div class="form-grid"><div class="field"><label>Nama fasilitas</label><input name="facilities[{{ $i }}][name]" value="{{ $facility['name'] ?? '' }}"></div><div class="field"><label>Lokasi file gambar</label><input name="facilities[{{ $i }}][image]" value="{{ $facility['image'] ?? '' }}" placeholder="assets/facility-lab.png"></div></div></div>@endforeach</section>
<section class="mz-card editor-section" id="berita"><div class="section-head"><div><h2>Berita & kegiatan</h2><p>Judul, ringkasan, gambar, dan isi lengkap berita.</p></div></div>@foreach($content['news'] as $i => $article)<div class="repeat-card"><h3>Berita {{ $i+1 }}</h3><div class="form-grid"><div class="field full"><label>Judul berita</label><input name="news[{{ $i }}][title]" value="{{ $article['title'] }}"></div><div class="field"><label>Kategori</label><input name="news[{{ $i }}][category]" value="{{ $article['category'] }}"></div><div class="field"><label>Tanggal</label><input name="news[{{ $i }}][date]" value="{{ $article['date'] }}"></div><div class="field full"><label>Gambar</label><input name="news[{{ $i }}][image]" value="{{ $article['image'] }}"></div><div class="field full"><label>Ringkasan</label><textarea name="news[{{ $i }}][excerpt]">{{ $article['excerpt'] }}</textarea></div><div class="field full"><label>Isi lengkap — pisahkan paragraf dengan baris baru</label><textarea name="news[{{ $i }}][content]">{{ implode("\n",$article['content']) }}</textarea></div><input type="hidden" name="news[{{ $i }}][slug]" value="{{ $article['slug'] }}"></div></div>@endforeach</section>
<section class="mz-card editor-section" id="kontak"><div class="section-head"><div><h2>PPDB & kontak</h2><p>Informasi yang dipakai pada tombol pendaftaran dan footer.</p></div></div><div class="form-grid"><div class="field"><label>Nomor WhatsApp</label><input name="phone" value="{{ $school['phone'] }}"></div><div class="field"><label>Email</label><input type="email" name="email" value="{{ $school['email'] }}"></div><div class="field full"><label>Alamat sekolah</label><input name="address" value="{{ $school['address'] }}"></div></div></section>
<div class="sticky-save"><button class="mz-button" type="submit">Simpan Perubahan</button></div></form></main></div></body></html>
