<?php
return [
    'name' => env('SCHOOL_NAME', 'SMA Harapan Bangsa'),
    'short_name' => env('SCHOOL_SHORT_NAME', 'Harapan Bangsa'),
    'level' => env('SCHOOL_LEVEL', 'Sekolah Menengah Atas'),
    'initials' => env('SCHOOL_INITIALS', 'HB'),
    'tagline' => env('SCHOOL_TAGLINE', 'Membentuk generasi berkarakter, berilmu, kreatif, dan siap bersaing di tingkat global.'),
    'hero_announcement' => 'Pendaftaran 2026/2027 telah dibuka',
    'hero_image' => 'assets/hero-school.jpg',
    'hero_caption' => 'Lingkungan belajar yang tumbuh bersama siswanya',
    'hero_primary_button' => 'Daftar Sekarang',
    'hero_secondary_button' => 'Kenali Sekolah',
    'hero_feature_title' => 'Pendidikan Berkualitas untuk Masa Depan',
    'hero_feature_text' => 'Kurikulum adaptif, pendampingan personal, dan lingkungan belajar modern.',
    'hero_stat_1_value' => '1.200+', 'hero_stat_1_label' => 'Siswa Aktif',
    'hero_stat_2_value' => '98%', 'hero_stat_2_label' => 'Lulus Tepat Waktu',
    'hero_stat_3_value' => '42', 'hero_stat_3_label' => 'Prestasi 2025',
    'trust_1_value' => 'A', 'trust_1_label' => 'Akreditasi Unggul',
    'trust_2_value' => '25+', 'trust_2_label' => 'Tahun Pengalaman',
    'trust_3_value' => '35', 'trust_3_label' => 'Guru Profesional',
    'trust_4_value' => '18', 'trust_4_label' => 'Ekstrakurikuler',
    'ppdb_label' => 'PPDB 2026',
    'principal' => env('SCHOOL_PRINCIPAL', 'Andi Rahman, M.Pd.'),
    'principal_quote' => env('SCHOOL_PRINCIPAL_QUOTE', 'Pendidikan adalah perjalanan untuk menyalakan potensi terbaik setiap anak.'),
    'profile_title' => 'Sekolah yang menumbuhkan potensi setiap siswa.',
    'profile' => 'SMA Harapan Bangsa menghadirkan pendidikan yang seimbang antara akademik, karakter, kreativitas, dan kecakapan abad ke-21. Setiap siswa didampingi untuk mengenali kekuatan dan merancang masa depannya.',
    'profile_image' => 'assets/school-thumb.jpg',
    'experience_years' => '25+',
    'benefits' => "Kurikulum Nasional Plus\nPembelajaran berbasis proyek\nKonseling dan mentoring\nPersiapan perguruan tinggi",
    'phone' => env('SCHOOL_PHONE', '62895321272932'),
    'email' => env('SCHOOL_EMAIL', 'info@harapanbangsa.sch.id'),
    'address' => env('SCHOOL_ADDRESS', 'Jl. Pendidikan No. 10, Kota Anda'),
];
