<!doctype html>
<script defer src="{{ asset('section-animations.js') }}?v={{ filemtime(public_path('section-animations.js')) }}"></script>
<script>window.youtubeArticleUrl=@json($article['youtube_url'] ?? '');</script><script defer src="{{ asset('youtube-video.js') }}?v={{ filemtime(public_path('youtube-video.js')) }}"></script>
<script defer src="{{ asset('related-news-carousel.js') }}?v={{ filemtime(public_path('related-news-carousel.js')) }}"></script>
<script>window.relatedNewsDescriptions=@json($related->pluck('excerpt')->values());</script>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{{ $article['excerpt'] }}"><title>{{ $article['title'] }} | {{ $school['short_name'] }}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('style.css') }}"><link rel="stylesheet" href="{{ asset('animations.css') }}"></head>
<body class="article-page"><header class="site-header scrolled"><div class="container navbar"><a class="brand" href="{{ route('home') }}"><div class="brand-mark">{{ $school['initials'] }}</div><div><strong>{{ $school['short_name'] }}</strong><span>{{ $school['level'] }}</span></div></a><a class="article-back" href="{{ route('home') }}#berita">← Kembali ke Berita</a></div></header>
<main><article><div class="article-hero"><div class="container article-heading"><div class="article-meta"><span>{{ $article['category'] }}</span><time>{{ $article['date'] }}</time></div><h1>{{ $article['title'] }}</h1><p>{{ $article['excerpt'] }}</p></div></div><div class="container article-body"><img class="article-cover" src="{{ asset($article['image']) }}" alt="{{ $article['title'] }}"><div class="article-copy">@foreach($article['content'] as $paragraph)<p>{{ $paragraph }}</p>@endforeach<div class="article-share"><strong>Bagikan kabar baik ini</strong><a href="https://wa.me/?text={{ urlencode($article['title'].' '.request()->url()) }}" target="_blank" rel="noopener">Bagikan melalui WhatsApp</a></div></div></div></article>
<section class="related-news"><div class="container"><div class="eyebrow">Berita Lainnya</div><h2>Jelajahi cerita lain</h2><div class="related-grid">@foreach($related as $item)<a href="{{ route('news.show', $item['slug']) }}"><img src="{{ asset($item['image']) }}" alt=""><div><span>{{ $item['category'] }}</span><h3>{{ $item['title'] }}</h3></div></a>@endforeach</div></div></section></main>
<footer><div class="container copyright">© {{ date('Y') }} {{ $school['name'] }}. Seluruh hak cipta dilindungi.</div></footer><script src="{{ asset('script.js') }}"></script></body></html>
